### ISSUE TITLE
Change user permissions for the Holmusk subscription

### ISSUE THREAD

**Issue by grazulis** [M-RIC-TRE/holmusk-change-approval#1]
### User Name

Nadia Lipunova

### User Email

nadia.lipunova@holmusk.com

### Change Details

Give the following user accounts owner role within the subscription for Holmusk in the MRIC TRE tenancy. 

Kahlil Abreu ([kahlil.abreu@holmusk.com](mailto:kahlil.abreu@holmusk.com))
Nitin Prakash ([nitin.prakash@holmusk.com](mailto:nitin.prakash@holmusk.com))
Callum Harding ([callum.harding@holmusk.com](mailto:callum.harding@holmusk.com)).

This is currently blocking development

### How quickly does this change need approval?

- [X] Critical Update
- [ ] Urgent
- [ ] Normal Priority
- [ ] Low Priority

**Comment by grazulis** [comment]
Approved by Jim Hughes by email, 1st Feb 2024 to @grazulis. Please action.

**Comment by david-salac** [comment]
Done
